### ISSUE TITLE
Parallel Wavenet

### ISSUE THREAD

**Issue by OssamaAlshabrawy** [munich-ai-labs/keras2-wavenet#6]
I'm just wondering whether there is an implementation for parallel wavenet especially you have the teacher model. Also the training and sampling is time-consuming according to the Deep Mind's blog for wavenet https://deepmind.com/blog/high-fidelity-speech-synthesis-wavenet/

**Comment by imdatsolak** [comment]
I don't have a parallel wavenet. It is quite difficult to do and would actually require an own kernel.
